import * as Native from "react-native";
import { ViewProps, TextProps, ScrollViewProps, TouchableOpacityProps, ImageProps, FlatListProps } from "react-native/types";
import * as NativeSlider from '@miblanchard/react-native-slider';
import { CreateView } from "./helper";

const AnimatedTouchable = Native.Animated.createAnimatedComponent(Native.TouchableOpacity);
export const View = CreateView<Native.View, ViewProps>(Native.View);
export const Slider = CreateView<NativeSlider.Slider, NativeSlider.SliderProps>(NativeSlider.Slider, "Slider");
export const Text = CreateView<Native.Text, TextProps>(Native.Text, "Text");
export const TextInput = CreateView<Native.TextInput, Native.TextInputProps>(Native.TextInput, "TextInput");
export const ScrollView = CreateView<Native.ScrollView, ScrollViewProps>(Native.ScrollView);
export const FlatList = CreateView<Native.FlatList, FlatListProps<any>>(Native.FlatList, "FlatList");
export const TouchableOpacity = CreateView<typeof Native.TouchableOpacity, TouchableOpacityProps>(Native.TouchableOpacity);
export const TouchableWithoutFeedback = CreateView<Native.TouchableWithoutFeedback, Native.TouchableWithoutFeedbackProps>(Native.TouchableOpacity);
export const TouchableNativeFeedback = CreateView<Native.TouchableNativeFeedback, Native.TouchableNativeFeedbackProps>(Native.TouchableOpacity);
export const Image = CreateView<Native.Image, ImageProps>(Native.Image);
export const AnimatedView = CreateView<Native.View, ViewProps>(Native.Animated.View, "AnimatedView");
export const AnimatedText = CreateView<Native.Text, TextProps>(Native.Animated.Text, "AnimatedText");
export const AnimatedTouchableOpacity = CreateView<typeof Native.TouchableOpacity, TouchableOpacityProps>(AnimatedTouchable, "AnimatedTouchableOpacity");
export const AnimatedScrollView = CreateView<Native.ScrollView, ScrollViewProps>(Native.Animated.ScrollView, "AnimatedScrollView");